source 'https://api.berkshelf.com'

cookbook 'yum-epel'
cookbook "java"
cookbook "boost", path: "./site-cookbooks/boost"
cookbook "cccc", path: "./site-cookbooks/cccc"
cookbook "cppcheck", path: "./site-cookbooks/cppcheck"
cookbook "devTools", path: "./site-cookbooks/devTools"
cookbook "doxygen", path: "./site-cookbooks/doxygen"
cookbook "eclipse", path: "./site-cookbooks/eclipse"
cookbook "ftp", path: "./site-cookbooks/ftp"
cookbook "gcc", path: "./site-cookbooks/gcc"
cookbook "ghostscript", path: "./site-cookbooks/ghostscript"
cookbook "gimp", path: "./site-cookbooks/gimp"
cookbook "glances", path: "./site-cookbooks/glances"
cookbook "graphviz", path: "./site-cookbooks/graphviz"
cookbook "gtest", path: "./site-cookbooks/gtest"
cookbook "httpd", path: "./site-cookbooks/httpd"
cookbook "ImageMagic", path: "./site-cookbooks/ImageMagick"
cookbook "inkscape", path: "./site-cookbooks/inkscape"
cookbook "ipa-pgothic-fonts", path: "./site-cookbooks/ipa-pgothic-fonts"
cookbook "jenkins", path: "./site-cookbooks/jenkins"
cookbook "latex", path: "./site-cookbooks/latex"
cookbook "lm_sensors", path: "./site-cookbooks/lm_sensors"
cookbook "mysql-server", path: "./site-cookbooks/mysql-server"
cookbook "ntp", path: "./site-cookbooks/ntp"
cookbook "prepareForRedmine", path: "./site-cookbooks/prepareForRedmine"
cookbook "PySensors", path: "./site-cookbooks/PySensors"
cookbook "redmine", path: "./site-cookbooks/redmine"
cookbook "redmine_plugins", path: "./site-cookbooks/redmine_plugins"
cookbook "ruby", path: "./site-cookbooks/ruby"
cookbook "ruby-env", path: "./site-cookbooks/ruby-env"
cookbook "valgrind", path: "./site-cookbooks/valgrind"
cookbook "vim", path: "./site-cookbooks/vim"
cookbook "xgdm_setting", path: "./site-cookbooks/xgdm_setting"
cookbook "prepareFiles", path: "./site-cookbooks/prepareFiles"
cookbook "qt", path: "./site-cookbooks/qt"
cookbook "pmd", path: "./site-cookbooks/pmd"
cookbook "tree", path: "./site-cookbooks/tree"
