default['ruby-env']['user'] = "redmine"
default['ruby-env']['group'] = "redmine"
default['ruby-env']['version'] = "1.9.3-p547"
default['ruby-env']['rbenv_url'] = "https://github.com/sstephenson/rbenv"
default['ruby-env']['ruby-build_url'] = "https://github.com/sstephenson/ruby-build"
