default['eclipse']['eclipse_base'] = "eclipse-standard-kepler-SR2-linux-gtk-x86_64"
default['eclipse']['eclipse_home'] = "/usr/local/bin/eclipse"
default['eclipse']['eclipse_download_url'] = "http://ftp.jaist.ac.jp/pub/eclipse/technology/epp/downloads/release/kepler/SR2"
default['eclipse']['cdt_version'] = "8.3.0"
default['eclipse']['cdt_download_url'] = "http://ftp.jaist.ac.jp/pub/eclipse/tools/cdt/releases/kepler/sr2"
default['eclipse'][''] = ""
default['eclipse'][''] = ""
